services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    networks:
      - kika-network

networks:
  kika-network:
    external: true