services:
  frontend:
    build:
      context: ..
      dockerfile: Dockerfile
      args:
        VITE_API_URL: http://kikapp.cloud/api
        VITE_TENANT_ID: 1
    image: ${{ secrets.DOCKER_USERNAME }}/kikapp-fe:latest
    container_name: kikapp-fe
    restart: always
    networks:
      - proxy
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s

networks:
  proxy:
    external: true