services:
  frontend:
    image: ${{ secrets.DOCKER_USERNAME }}/kikapp-fe:latest
    container_name: kikapp-fe
    restart: always
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - ./.env:/var/www/html/.env:ro
    networks:
      - proxy

networks:
  proxy:
    external: true